apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kgs-upload-pods
  namespace: {{NAMESPACE}}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{NAMESPACE}}
roleRef:
  kind: Role
  name: kgs-upload
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{NAMESPACE}}
  name: kgs-upload
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]