apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kgs-upload-ingress
  namespace: {{NAMESPACE}}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/uploadDump"
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - your-hostname.com
    secretName: tls-secret
  rules:
  - host: your-hostname.com
    http:
      paths:
        - path: "/uploadDump(/|$)(.*)"
          backend:
            service: 
              name: kgs-upload-service
              port: 
                number: 80
          pathType: "Prefix"